dataset: kth

dataset_path: C:\Users\aysha\Cuda Lab\KTH

epochs: 100

learning_rate: 0.001

seq_len: 10

prediction_len: 10

batch_size: 1

# Scheduler
factor: 0.1

patience: 10

# Logging
log_freq: 100
